### ISSUE TITLE
Can't post a transaction: 403 error on OPTIONS request without CORS headers

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternal#206]
Chrome console output:
```
OPTIONS https://aeternal.io/v2/transactions 403 (Forbidden)
```
```
Access to XMLHttpRequest at 'https://aeternal.io/v2/transactions' from
origin 'http://localhost:8080' has been blocked by CORS policy:
Response to preflight request doesn't pass access control check:
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

The same error when using https://testnet.mdw.aepps.com/ instead of https://sdk-testnet.aepps.com/ in the Base aepp:
```
OPTIONS https://testnet.mdw.aepps.com/v2/transactions 403
```
```
Access to XMLHttpRequest at 'https://testnet.mdw.aepps.com/v2/transactions' from
origin 'http://localhost:8080' has been blocked by CORS policy:
Response to preflight request doesn't pass access control check:
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by johnsnewby** [comment]
Can I have a step to reproduce?

**Comment by davidyuk** [comment]
I assume that you shouldn't be able to publish any transaction through middleware using sdk in a web browser (it should be a cross-domain request). I will provide a more accurate reproduction if you won't be able to reproduce that.

**Comment by davidyuk** [comment]
I have created reproduction here: https://github.com/davidyuk/vue-reproductions/tree/middleware-post-transaction

![Screenshot 2019-10-30 at 08 18 19](https://user-images.githubusercontent.com/9007851/67836870-07b56680-faee-11e9-984f-54067a1deb58.png)

for some reason, I have a CORS issue even using https://node.testnet.aeternal.io

**Comment by johnsnewby** [comment]
This is fixed now, correct? Closing this issue, re-open if necessary
