### ISSUE TITLE
Error with db and key block after docker-compose up

### ISSUE THREAD

**Issue by tima-t** [aeternity/aeternal#250]
**Note: for support questions, please use the [forum](https://forum.aeternity.com)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
After running docker-compose up in the root folder with the default configs, I have the following db error
middleware_1  | 2019-12-17T17:39:14.514634226+00:00 ERROR aeternal::loader - Couldn't load generation -1 from DB
middleware_1  | 2019-12-17T17:39:20.537184677+00:00 ERROR aeternal::models - Error loading key block: NotFound

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Node Version: v0.0.0
  - Protocol Version: 1
  - Sophia Compiler version: v0.0.0
  - Rust version: v0.00 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)

**Comment by noandrea** [comment]
is it the same of #249 ?

**Comment by tima-t** [comment]
Yes, excuse me.
We can close this one.
